// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseImg: typeof import('./src/components/base-img/BaseImg.vue')['default']
    ClassifyCategoryInfos: typeof import('./src/components/classify-sort/ClassifyCategoryInfos.vue')['default']
    ClassifyDistricts: typeof import('./src/components/classify-sort/ClassifyDistricts.vue')['default']
    ClassifySort: typeof import('./src/components/classify-sort/ClassifySort.vue')['default']
    ClassifyStores: typeof import('./src/components/classify-sort/ClassifyStores.vue')['default']
    EmptyError: typeof import('./src/components/empty-error/EmptyError.vue')['default']
    MediaPreview: typeof import('./src/components/media-preview/MediaPreview.vue')['default']
    Minicard: typeof import('./src/components/minicard/Minicard.vue')['default']
    ProductCell: typeof import('./src/components/product-cell/ProductCell.vue')['default']
    ProductPrice: typeof import('./src/components/product-price/ProductPrice.vue')['default']
    ProductPrice2: typeof import('./src/components/product-price/ProductPrice2.vue')['default']
    ProductPrice3: typeof import('./src/components/product-price/ProductPrice3.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/SearchBar.vue')['default']
    TitleBar: typeof import('./src/components/title-bar/TitleBar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanImage: typeof import('vant/es')['Image']
    VanIndexAnchor: typeof import('vant/es')['IndexAnchor']
    VanIndexBar: typeof import('vant/es')['IndexBar']
    VanList: typeof import('vant/es')['List']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VideoPlayer: typeof import('./src/components/video-player/VideoPlayer.vue')['default']
  }
}
